"""
dev_release.py - Lokaler Test-Build-Workflow fuer OTA Self-Update Tests.

Zweck:
  - Baut alle Firmware-Varianten (App-Images).
  - Kopiert die firmware.bin-Dateien mit passenden Namen nach
    tools/local_testserver/v9.9.9/, damit sie ueber den simulierten
    Testserver per OTA Self-Update getestet werden koennen.

Es werden dabei bewusst KEINE Git-Aktionen (Tag/Commit/Push) und KEIN
GitHub Release ausgefuehrt. Der stabile Webinstaller
(docs/webinstaller-dev, docs/webinstaller, release.py) wird nicht
angefasst.

Der lokale Testserver-Host wird NICHT mehr fest im Firmware-Header
verdrahtet, sondern von diesem Skript vor dem Build in eine generierte,
git-ignorierte Header-Datei geschrieben (ota_local_server_generated.h).
So funktioniert derselbe Testbuild egal ob im Buero (10.10.x.x) oder
zu Hause (192.168.x.x), ohne den Header von Hand anzupassen.

DEFAULT PORT 8000

Nutzung:
    python tools/dev_release.py
    python tools/dev_release.py --server-ip 192.168.178.123
    python tools/dev_release.py --server-ip 192.168.178.123 --port 8080

Optional:
    python tools/dev_release.py --skip-build
"""

import argparse
import shutil
import socket
import subprocess
import sys
from pathlib import Path


# Maps PlatformIO env name -> target file prefix used for the test server.
# NOTE: these are the *_dev envs (see platformio.ini), which extend the
# normal envs and add -D OTA_DEBUG_LOCAL_SERVER. Building the plain envs
# here would bake in the GitHub URL, not the local test server.
ENV_MAPPING = {
    "esp32_dev": "esp32-sh1106",
    "esp32-st7789_dev": "esp32-st7789",
    "esp32-s3_dev": "esp32-s3-sh1106",
    "esp32-s3-st7789_dev": "esp32-s3-st7789",
}

TOOLS_DIR = Path(__file__).resolve().parent
PROJECT_DIR = TOOLS_DIR.parent
BUILD_DIR = PROJECT_DIR / ".pio" / "build"

# Fixed test folder — always the same name, not tied to a real version.
LOCAL_TESTSERVER_DIR = TOOLS_DIR / "local_testserver" / "v9.9.9"

# Generated header consumed by the firmware's OTA_DEBUG_LOCAL_SERVER branch.
# NOTE: adjust this path to match where your project's headers actually live.
LOCAL_SERVER_HEADER = PROJECT_DIR / "include" / "ota_local_server_generated.h"

DEFAULT_PORT = 8000


def detect_local_ip():
    """Best-effort detection of this machine's current LAN IP.

    Opens a UDP socket toward a public address without actually sending
    any traffic, just to ask the OS which local interface/IP would be
    used for outbound traffic. Works the same whether on the office or
    home network.
    """
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        sock.connect(("8.8.8.8", 80))
        return sock.getsockname()[0]
    except OSError:
        return "127.0.0.1"
    finally:
        sock.close()


def write_local_server_header(ip, port):
    print(f"\n=== Schritt 1/3: Test-Server-Adresse in Header schreiben ===")

    LOCAL_SERVER_HEADER.parent.mkdir(parents=True, exist_ok=True)
    url_base = f"http://{ip}:{port}/"
    content = (
        "// Auto-generated by tools/dev_release.py - do not edit by hand.\n"
        "// Do not commit: add this file to .gitignore.\n"
        "#pragma once\n"
        f'#define OTA_LOCAL_SERVER_URL_BASE "{url_base}"\n'
    )
    LOCAL_SERVER_HEADER.write_text(content, encoding="utf-8")
    print(f"  {LOCAL_SERVER_HEADER.relative_to(PROJECT_DIR)} -> {url_base}")


def run(cmd, cwd=None):
    """Run a command and abort on failure."""
    print(f"  $ {' '.join(cmd)}")
    try:
        subprocess.run(cmd, check=True, cwd=cwd or PROJECT_DIR)
    except FileNotFoundError:
        print(f"\nFEHLER: Befehl '{cmd[0]}' wurde nicht gefunden.")
        sys.exit(1)


def git_branch():
    """Return the currently checked-out branch."""
    result = subprocess.run(
        ["git", "branch", "--show-current"],
        cwd=PROJECT_DIR,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def check_dev_branch():
    """Safety check: never build/test local OTA firmware from the stable branch."""
    branch = git_branch()
    print(f"  Aktueller Git-Branch: {branch or '<detached HEAD>'}")

    if branch == "main":
        print("\nFEHLER: dev_release.py darf nicht auf dem stabilen Branch 'main' laufen.")
        print("Bitte auf 'dev' oder einen Feature-Branch wechseln.")
        sys.exit(1)


def build_all():
    print("\n=== Schritt 2/3: Firmware-Varianten bauen ===")

    for env_name in ENV_MAPPING:
        print(f"\n  -- {env_name} (App) --")
        run(["pio", "run", "-e", env_name], cwd=PROJECT_DIR)


def copy_to_local_testserver():
    print(f"\n=== Schritt 3/3: Firmware nach {LOCAL_TESTSERVER_DIR.relative_to(PROJECT_DIR)} kopieren ===")

    LOCAL_TESTSERVER_DIR.mkdir(parents=True, exist_ok=True)

    for env_name, target_name in ENV_MAPPING.items():
        source = BUILD_DIR / env_name / "firmware.bin"

        if not source.exists():
            print(f"FEHLER: firmware.bin fehlt in {BUILD_DIR / env_name}")
            print("(Vorher bauen, oder --skip-build nur nutzen, wenn bereits gebaut wurde.)")
            sys.exit(1)

        target = LOCAL_TESTSERVER_DIR / f"{target_name}-firmware.bin"
        shutil.copy2(source, target)
        print(f"  {env_name}/firmware.bin -> {target.relative_to(PROJECT_DIR)}")


def main():
    parser = argparse.ArgumentParser(
        description="Lokaler Build- und Kopier-Workflow fuer OTA Self-Update Tests"
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Bauen ueberspringen (nutzt vorhandene .pio/build-Dateien)",
    )
    parser.add_argument(
        "--server-ip",
        help="IP des lokalen Testservers (Standard: automatisch erkannte LAN-IP)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help=f"Port des lokalen Testservers (Standard: {DEFAULT_PORT})",
    )

    args = parser.parse_args()
    server_ip = args.server_ip or detect_local_ip()

    print("=== Dev-Testbuild fuer lokalen OTA-Testserver ===")
    print(f"  Test-Server: http://{server_ip}:{args.port}/")

    check_dev_branch()
    write_local_server_header(server_ip, args.port)

    if not args.skip_build:
        build_all()
    else:
        print("\n--skip-build gesetzt: verwende vorhandene .pio/build-Ausgaben.")

    copy_to_local_testserver()

    print(f"\nFertig! Testbuilds liegen in {LOCAL_TESTSERVER_DIR.relative_to(PROJECT_DIR)}/")


if __name__ == "__main__":
    main()