[env:esp32s3]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    ArduinoJson
    Adafruit PN532
    Adafruit SSD1306
    Adafruit GFX Library
    Adafruit NeoPixel
    tzapu/WiFiManager @ ^2.0.5
