[platformio]
default_envs = esp32

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
  Adafruit PN532
  Adafruit SSD1306
  Adafruit SH110X
  Adafruit GFX Library
  Adafruit NeoPixel
  tzapu/WiFiManager @ ^2.0.5
  https://github.com/me-no-dev/AsyncTCP.git
  https://github.com/me-no-dev/ESPAsyncWebServer.git
  bblanchon/ArduinoJson@^7.4.2
board_build.filesystem = littlefs
board_build.partitions = partitions_ota_littlefs.csv
extra_scripts = pre:tools/git_version.py , pre:scripts/gzip_asset.py
build_flags =    ; <-- leer lassen

[env:esp32]
build_flags = ${env.build_flags}

[env:ssd1306]
build_flags =
  ${env.build_flags}
  -DDISPLAY_TYPE=DISPLAY_TYPE_SSD1306
