# tools/git_version.py
import os, subprocess, re
from SCons.Script import Import
Import("env")

def run(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT).decode().strip()
    except Exception:
        return ""

# 1) Werte aus Git holen (best effort)
git_ver  = run("git describe --tags --always --dirty")  # z.B. v0.1a-3-gabc1234
git_hash = run("git rev-parse --short HEAD")            # z.B. abc1234

# 2) Fallbacks, z.B. in CI/ZIP ohne .git
if not git_ver:
    git_ver = os.environ.get("GITHUB_REF_NAME", "") or "0.0.0"
if not git_hash:
    git_hash = "nogit"

# 3) Nur sichere Zeichen zulassen (Datei/Code freundlich)
def clean(s): return re.sub(r'[^0-9A-Za-z._+-]', '-', s)
git_ver  = clean(git_ver)
git_hash = clean(git_hash)

# 4) Header-Datei erzeugen
proj_inc = env.subst("$PROJECT_INCLUDE_DIR")
out_path = os.path.join(proj_inc, "version_auto.h")

os.makedirs(proj_inc, exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by tools/git_version.py – DO NOT EDIT\n")
    f.write("#pragma once\n")
    f.write(f'#define FIRMWARE_VERSION "{git_ver}"\n')
    f.write(f'#define GIT_HASH "{git_hash}"\n')

print(f"[git_version] Wrote {out_path}: FIRMWARE_VERSION={git_ver}, GIT_HASH={git_hash}")

# Optional: Falls du zusätzlich -D willst, kannst du das tun – aber NICHT nötig.
# env.Append(CPPDEFINES=[f'FIRMWARE_VERSION="{git_ver}"', f'GIT_HASH="{git_hash}"'])
