[platformio]
default_envs = esp32, esp32-s3, esp32-st7789, esp32-s3-st7789

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
  Adafruit PN532
  Adafruit GFX Library
  Adafruit NeoPixel
  tzapu/WiFiManager @ ^2.0.5
  https://github.com/me-no-dev/AsyncTCP.git
  https://github.com/me-no-dev/ESPAsyncWebServer.git
  bblanchon/ArduinoJson@^7.4.2
  knolleary/PubSubClient
board_build.filesystem = littlefs

extra_scripts = pre:tools/git_version.py , pre:scripts/gzip_asset.py

build_flags =
  -D MQTT_MAX_PACKET_SIZE=1024



;ESP32 Devkit V1 for 128x64 SSD1306 OLED display
[env:esp32]
build_src_filter = +<**/*.cpp> +<display/oled/*> -<display/st7789/*>
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.partitions = partitions_ota_littlefs_esp32dev.csv

lib_deps =
  ${env.lib_deps} 
  Adafruit SSD1306
  Adafruit SH110X

build_flags = 
  ${env.build_flags}
  -DBOARD_VARIANT="\"dev-kit-v1\""
  -DDISPLAY_TYPE=DISPLAY_TYPE_SSD1306



;ESP32 Devkit V1 for 128x64 SH110X OLED display
[env:esp32-st7789]
build_src_filter = +<**/*.cpp> +<display/st7789/*> -<display/oled/*>
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.partitions = partitions_ota_littlefs_esp32dev.csv

board_upload.flash_size = 4MB
board_build.flash_size = 4MB

lib_deps =
  ${env.lib_deps}
  lovyan03/LovyanGFX

build_flags = 
  ${env.build_flags}
  -DBOARD_VARIANT="\"dev-kit-v1\""
  -DDISPLAY_TYPE=DISPLAY_TYPE_ST7789
  -DTFT_CS=5
  -DTFT_DC=32
  -DTFT_RST=33
  -DNFC_SCK=14
  -DNFC_MISO=12
  -DNFC_MOSI=13


  
;ESP32-S3 version for 128x64 SH110X OLED display, tested with ESP32-S3 Zero
[env:esp32-s3]
build_src_filter = +<**/*.cpp> +<display/oled/*> -<display/st7789/*>
board = esp32-s3-devkitc-1
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions_ota_littlefs_esp32s3.csv

board_upload.flash_size = 4MB
board_build.flash_size = 4MB
monitor_filters = esp32_exception_decoder

lib_deps =
  ${env.lib_deps} 
  Adafruit SH110X

build_flags = ${env.build_flags} 
  -DDISPLAY_TYPE=DISPLAY_TYPE_SH1106
  -DSDA_PIN=13
  -DSCL_PIN=12
  -DLED_PIN=2
  -DNFC_LED_PIN=1
  -DBTN_PIN=7
  -DBUZ_PIN=8
  ;-DSPI_SCK=3
  ;-DSPI_MISO=4
  ;-DSPI_MOSI=5
  -DPN532_CS=6
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_VARIANT="\"esp32-s3-zero\""



; ESP32-S3 version for ST7789. Tested with ST7789 170x320 display, an ESP32-S3 Zero
[env:esp32-s3-st7789]
build_src_filter = +<**/*.cpp> +<display/st7789/*> -<display/oled/*>
board = esp32-s3-devkitc-1
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions_ota_littlefs_esp32s3.csv

board_upload.flash_size = 4MB
board_build.flash_size = 4MB
monitor_filters = esp32_exception_decoder

lib_deps =
  ${env.lib_deps}
  lovyan03/LovyanGFX

build_flags = ${env.build_flags} 
  -DDISPLAY_TYPE=DISPLAY_TYPE_ST7789
  -DLED_PIN=2
  -DNFC_LED_PIN=1
  -DBTN_PIN=7
  -DBUZ_PIN=8
  -DNFC_SCK=3
  -DNFC_MISO=4
  -DNFC_MOSI=5
  -DPN532_CS=6
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -D MQTT_MAX_PACKET_SIZE=1024
  -DBOARD_VARIANT="\"esp32-s3-zero\""
  -DTFT_CS=40
  -DTFT_DC=41
  -DTFT_RST=42
  -DTFT_SCK=38
  -DTFT_MOSI=39
  -DTFT_MISO=-1
