[platformio]
default_envs = esp32, esp32-s3

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
  Adafruit PN532
  Adafruit GFX Library
  Adafruit NeoPixel
  tzapu/WiFiManager @ ^2.0.5
  https://github.com/me-no-dev/AsyncTCP.git
  https://github.com/me-no-dev/ESPAsyncWebServer.git
  bblanchon/ArduinoJson@^7.4.2
  knolleary/PubSubClient
board_build.filesystem = littlefs

extra_scripts = pre:tools/git_version.py , pre:scripts/gzip_asset.py
build_flags =    ; <-- leer lassen




[env:esp32]
src_filter = +<**/*.cpp> +<display/oled/*> -<display/gc9a01/*>
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.partitions = partitions_ota_littlefs_esp32dev.csv

lib_deps =
  ${env.lib_deps} 
  Adafruit SSD1306
  Adafruit SH110X

build_flags = 
  ${env.build_flags}
  -D MQTT_MAX_PACKET_SIZE=1024
  -DBOARD_VARIANT="\"dev-kit-v1\""
  -DDISPLAY_TYPE=DISPLAY_TYPE_SSD1306


  

[env:esp32-s3]
src_filter = +<**/*.cpp> +<display/oled/*> -<display/gc9a01/*>
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions_ota_littlefs_esp32s3.csv
monitor_filters = esp32_exception_decoder

lib_deps =
  ${env.lib_deps} 
  Adafruit SH110X

build_flags = ${env.build_flags} 
  -DDISPLAY_TYPE=DISPLAY_TYPE_SH1106
  -DSDA_PIN=13
  -DSCL_PIN=12
  -DLED_PIN=2
  -DNFC_LED_PIN=1
  -DBTN_PIN=7
  -DBUZ_PIN=8
  -DSPI_SCK=3
  -DSPI_MISO=4
  -DSPI_MOSI=5
  -DPN532_CS=6
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -D MQTT_MAX_PACKET_SIZE=1024
  -DBOARD_VARIANT="\"esp32-s3-supermini\""




[env:esp32-s3-gc9a01]
src_filter = +<**/*.cpp> +<display/gc9a01/*> -<display/oled/*>
lib_deps =
  ${env.lib_deps}
  lovyan03/LovyanGFX
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions_ota_littlefs_esp32s3.csv
monitor_filters = esp32_exception_decoder

build_flags = ${env.build_flags} 
  -DDISPLAY_TYPE=DISPLAY_TYPE_GC9A01
  -DLED_PIN=2
  -DNFC_LED_PIN=1
  -DBTN_PIN=7
  -DBUZ_PIN=8
  -DSPI_SCK=3
  -DSPI_MISO=4
  -DSPI_MOSI=5
  -DPN532_CS=6
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -D MQTT_MAX_PACKET_SIZE=1024
  -DBOARD_VARIANT="\"esp32-s3-supermini\""
  -DTFT_CS=40
  -DTFT_DC=41
  -DTFT_RST=42
  -DTFT_SCK=38
  -DTFT_MOSI=39
  -DTFT_MISO=-1
